# Generated by Django 6.0.1 on 2026-01-12 14:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID изображения')),
                ('file_path', models.CharField(max_length=500, verbose_name='Путь к файлу')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID услуги')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('master_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID мастера')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('specialization', models.CharField(max_length=255, verbose_name='Специализация')),
                ('experience_years', models.PositiveIntegerField(verbose_name='Опыт работы (лет)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masters', to='salon.image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='MasterService',
            fields=[
                ('master_service_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID связи')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_services', to='salon.master', verbose_name='Мастер')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_services', to='salon.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Связь мастер-услуга',
                'verbose_name_plural': 'Связи мастер-услуга',
                'ordering': ['master', 'service'],
                'unique_together': {('master', 'service')},
            },
        ),
        migrations.AddField(
            model_name='master',
            name='services',
            field=models.ManyToManyField(related_name='masters', through='salon.MasterService', to='salon.service', verbose_name='Услуги'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID пользователя')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('role', models.CharField(choices=[('client', 'Клиент'), ('admin', 'Администратор')], default='client', max_length=10, verbose_name='Роль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('favorite_masters', models.ManyToManyField(blank=True, related_name='favorited_by_users', to='salon.master', verbose_name='Избранные мастера')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID отзыва')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='salon.master', verbose_name='Мастер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='salon.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID записи')),
                ('appointment_datetime', models.DateTimeField(verbose_name='Дата и время записи')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждена'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='salon.master', verbose_name='Мастер')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='salon.service', verbose_name='Услуга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='salon.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-appointment_datetime'],
            },
        ),
    ]
