# Generated by Django 6.0.1 on 2026-01-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_remove_user_favorite_masters'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='related_services',
            field=models.ManyToManyField(blank=True, to='salon.service', verbose_name='Связанные услуги'),
        ),
    ]
