# Generated by Django 6.0.1 on 2026-01-12 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('salon', '0003_service_related_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file_path',
            field=models.ImageField(upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='ChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('created', 'Создан'), ('updated', 'Обновлен'), ('deleted', 'Удален')], max_length=20, verbose_name='Действие')),
                ('changed_by', models.CharField(blank=True, max_length=255, verbose_name='Изменено пользователем')),
                ('changes', models.JSONField(default=dict, verbose_name='Изменения')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время изменения')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'История изменений',
                'verbose_name_plural': 'История изменений',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='salon_chang_content_e00a25_idx')],
            },
        ),
    ]
